valor = input('Digite algo: ')
print('O tipo desse valor é: ', type(valor))
print(f'Só tem espaços? ', valor.strip())
print(f'É um alfabeto? ', valor.isalpha())
print(f'É um número? ', valor.isnumeric())
print(f'É um alfanúmerico? ', valor.isalnum())
print(f'Está em maiúsculo?' , valor.isupper())
print(f'Está em minúsculo? ', valor.islower())
print(f'Está capitalizada? ', valor.istitle())
